"""Heatmap, tree, and pseudotime compatibility wrappers."""

from typing import Any


def marker_heatmap(
    store: Any,
    *,
    from_assay: str | None = None,
    group_key: str | None = None,
    cell_key: str | None = None,
    topn: int = 5,
    log_transform: bool = True,
    vmin: float = -1,
    vmax: float = 2,
    savename: str | None = None,
    save_dpi: int = 300,
    show_fig: bool = True,
    **heatmap_kwargs: Any,
) -> None:
    """Facade for ``DataStore.plot_marker_heatmap``."""
    store.plot_marker_heatmap(
        from_assay=from_assay,
        group_key=group_key,
        cell_key=cell_key,
        topn=topn,
        log_transform=log_transform,
        vmin=vmin,
        vmax=vmax,
        savename=savename,
        save_dpi=save_dpi,
        show_fig=show_fig,
        **heatmap_kwargs,
    )


def cluster_tree(
    store: Any,
    *,
    from_assay: str | None = None,
    cell_key: str | None = None,
    feat_key: str | None = None,
    cluster_key: str | None = None,
    fill_by_value: str | None = None,
    force_ints_as_cats: bool = True,
    width: float = 1,
    lvr_factor: float = 0.5,
    vert_gap: float = 0.2,
    min_node_size: float = 10,
    node_size_multiplier: float = 10_000.0,
    node_power: float = 1.2,
    root_size: float = 100,
    non_leaf_size: float = 10,
    show_labels: bool = True,
    fontsize: float = 10,
    root_color: str = "#C0C0C0",
    non_leaf_color: str = "k",
    cmap: str = "tab20",
    color_key: dict[str, str] | None = None,
    edgecolors: str = "k",
    edgewidth: float = 1,
    alpha: float = 0.7,
    figsize: tuple[float, float] = (5, 5),
    ax: Any = None,
    show_fig: bool = True,
    savename: str | None = None,
    save_dpi: int = 300,
) -> None:
    """Facade for ``DataStore.plot_cluster_tree``."""
    store.plot_cluster_tree(
        from_assay=from_assay,
        cell_key=cell_key,
        feat_key=feat_key,
        cluster_key=cluster_key,
        fill_by_value=fill_by_value,
        force_ints_as_cats=force_ints_as_cats,
        width=width,
        lvr_factor=lvr_factor,
        vert_gap=vert_gap,
        min_node_size=min_node_size,
        node_size_multiplier=node_size_multiplier,
        node_power=node_power,
        root_size=root_size,
        non_leaf_size=non_leaf_size,
        show_labels=show_labels,
        fontsize=fontsize,
        root_color=root_color,
        non_leaf_color=non_leaf_color,
        cmap=cmap,
        color_key=color_key,
        edgecolors=edgecolors,
        edgewidth=edgewidth,
        alpha=alpha,
        figsize=figsize,
        ax=ax,
        show_fig=show_fig,
        savename=savename,
        save_dpi=save_dpi,
    )


def pseudotime_heatmap(
    store: Any,
    *,
    from_assay: str | None = None,
    cell_key: str | None = None,
    feat_key: str | None = None,
    feature_cluster_key: str | None = None,
    pseudotime_key: str | None = None,
    show_features: list[str] | None = None,
    width: int = 5,
    height: int = 10,
    vmin: float = -2.0,
    vmax: float = 2.0,
    heatmap_cmap: str | None = None,
    pseudotime_cmap: str | None = None,
    clusterbar_cmap: str | None = None,
    tick_fontsize: int = 10,
    axis_fontsize: int = 12,
    feature_label_fontsize: int = 12,
    savename: str | None = None,
    save_dpi: int = 300,
    show_fig: bool = True,
) -> None:
    """Facade for ``DataStore.plot_pseudotime_heatmap``."""
    store.plot_pseudotime_heatmap(
        from_assay=from_assay,
        cell_key=cell_key,
        feat_key=feat_key,
        feature_cluster_key=feature_cluster_key,
        pseudotime_key=pseudotime_key,
        show_features=show_features,
        width=width,
        height=height,
        vmin=vmin,
        vmax=vmax,
        heatmap_cmap=heatmap_cmap,
        pseudotime_cmap=pseudotime_cmap,
        clusterbar_cmap=clusterbar_cmap,
        tick_fontsize=tick_fontsize,
        axis_fontsize=axis_fontsize,
        feature_label_fontsize=feature_label_fontsize,
        savename=savename,
        save_dpi=save_dpi,
        show_fig=show_fig,
    )
