ignore:
  - "tests/*"
  - "setup.py"

github_checks: false

coverage:
  precision: 2
  round: down
  range: "85...90"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: 95%
        threshold: 0%
        informational: true
