from typing import TYPE_CHECKING

import numpy as np
from scipy.sparse import csr_matrix

from ...graph.distances import validate_distance_provenance
from ...graph.feature_projection import resolve_native_graph_inputs
from ...graph.state import (
    read_assay_state,
    resolve_graph_selection,
)
from ...metadata.artifacts import (
    artifact_values,
    column_display,
    continuous_display,
    link_cell_data_column,
    plan_cell_data_artifact,
    write_cell_data_artifact,
)
from ...metadata.arguments import TsneArguments, UmapArguments
from ...storage.artifacts import (
    ArtifactRef,
    artifact_group,
    artifact_path,
    fingerprint_array,
    inspect_artifact,
)
from ...storage.types import as_zarr_array, as_zarr_group
from ...utils.logging import logger, progress_enabled

if TYPE_CHECKING:
    from .graph import _GraphOperationsMixin as _EmbeddingOperationsBase
else:
    _EmbeddingOperationsBase = object


class _EmbeddingOperationsMixin(_EmbeddingOperationsBase):
    def _get_ini_embed(
        self,
        from_assay: str,
        cell_key: str,
        graph: ArtifactRef,
        n_comps: int,
    ) -> tuple[np.ndarray, ArtifactRef]:
        """Runs PCA on kmeans cluster centers and ascribes the PC values to
        individual cells based on their cluster labels. This is used in
        `run_umap` and `run_tsne` for initial embedding of cells. Uses
        `rescale_array` to reduce the magnitude of extreme values.

        Args:
            from_assay: Name fo the assay for which Kmeans was fit.
            cell_key: Cell key used.
            graph: Graph whose rows the initialization must match.
            n_comps: Number of PC components to use

        Returns:
            Matrix with n_comps dimensions representing initial embedding of cells.
        """
        from ...embeddings.initialization import initial_embedding

        state = read_assay_state(self.zw, from_assay)
        if (
            state is None
            or not state.matches(cell_key)
            or state.embedding_initialization is None
        ):
            raise KeyError("AssayState has no embedding initialization")
        initialization = state.embedding_initialization
        initialization_status = inspect_artifact(self.zw, initialization)
        if graph.kind == "connectivity_map":
            lineage = resolve_native_graph_inputs(self.zw, graph)
            raw_reduction = (initialization_status.inputs or {}).get("reduction")
            if (
                lineage.reduction is None
                or not isinstance(raw_reduction, dict)
                or ArtifactRef.from_dict(raw_reduction) != lineage.reduction
            ):
                raise ValueError(
                    "Embedding initialization does not belong to the graph reduction"
                )
        kmeans_grp = artifact_group(self.zw, initialization)
        cluster_centers = np.asarray(
            as_zarr_array(
                kmeans_grp["cluster_centers"],
                name="cluster_centers",
            )[:]
        )
        clusters = np.asarray(
            as_zarr_array(kmeans_grp["cluster_labels"], name="cluster_labels")[:]
        )
        return initial_embedding(cluster_centers, clusters, n_comps), initialization

    def run_tsne(
        self,
        graph: ArtifactRef | None = None,
        *,
        from_assay: str | None = None,
        cell_key: str | None = None,
        symmetric_graph: bool = False,
        graph_upper_only: bool = False,
        ini_embed: np.ndarray | None = None,
        tsne_dims: int = 2,
        lambda_scale: float = 1.0,
        max_iter: int = 500,
        early_iter: int = 200,
        alpha: int = 10,
        box_h: float = 0.7,
        temp_file_loc: str = ".",
        label: str = "tSNE",
        verbose: bool = True,
        parallel: bool = False,
        nthreads: int | None = None,
        invalidate_cache: bool = False,
    ) -> ArtifactRef:
        """Run SGtSNE-pi (Read more here:
        https://github.com/fcdimitr/sgtsnepi/tree/v1.0.1). This is an
        implementation of tSNE that runs directly on graph structures. We use
        connectivity graphs generated by graph-construction methods to create a
        layout of cells using tSNE algorithm. This function makes a system call to sgtSNE
        binary. To get a better understanding of how the parameters affect the
        embedding, check this out: http://t-sne-pi.cs.duke.edu/

        Args:
            graph: Connectivity map or integrated graph to embed. The current
                   analysis chain of the assay is used when omitted.
            from_assay: Name of assay to be used. If no value is provided then the default assay will be used.
            cell_key: Cell key. Should be same as the one that was used in the desired graph. (Default value: 'I')
            symmetric_graph: This parameter is forwarded to `load_graph` and is same as there. (Default value: False)
            graph_upper_only: This parameter is forwarded to `load_graph` and is same as there. (Default value: False)
            ini_embed: Initial embedding coordinates for the cells in cell_key. Should have the same number of columns
                       as tsne_dims. If not value is provided then the initial embedding is obtained using
                       `get_ini_embed`.
            tsne_dims: Number of tSNE dimensions to compute (Default value: 2)
            lambda_scale: λ rescaling parameter (Default value: 1.0)
            max_iter: Maximum number of iterations (Default value: 500)
            early_iter: Number of early exaggeration iterations (Default value: 200)
            alpha: Early exaggeration multiplier (Default value: 10)
            box_h: Grid side length (accuracy control). Lower values might drastically slow down
                   the algorithm (Default value: 0.7)
            temp_file_loc: Location of temporary file. By default, these files will be created in the current working
                           directory. These files are deleted before the method returns.
            label: base label for tSNE dimensions in the cell metadata column (Default value: 'tSNE')
            verbose: If True (default) then the full log from SGtSNEpi algorithm is shown.
            parallel: Whether to run tSNE in parallel mode. Setting value to True will use `nthreads` threads.
                      The results are not reproducible in parallel mode. (Default value: False)
            nthreads: If parallel=True then this number of threads will be used to run tSNE. By default the `nthreads`
                      attribute of the class is used. (Default value: None)

        Returns:
            Reference to the embedding artifact backing the layout columns.
        """
        selection = resolve_graph_selection(
            self,
            graph,
            from_assay=from_assay,
            cell_key=cell_key,
        )
        from_assay = selection.from_assay
        cell_key = selection.cell_key
        graph_input = selection.graph_ref
        graph_matrix = self.load_graph(
            graph_input,
            from_assay=from_assay,
            cell_key=cell_key,
            symmetric=symmetric_graph,
            upper_only=graph_upper_only,
        )
        user_initialization = ini_embed is not None
        initialization_input: object
        if ini_embed is None:
            ini_embed, initialization_input = self._get_ini_embed(
                from_assay,
                cell_key,
                graph_input,
                tsne_dims,
            )
        if ini_embed.shape != (graph_matrix.shape[0], tsne_dims):
            raise ValueError(
                "Initial embedding has an invalid shape; expected "
                f"{(graph_matrix.shape[0], tsne_dims)}"
            )
        if user_initialization:
            initialization_input = {"value_fingerprint": fingerprint_array(ini_embed)}
        if parallel:
            if nthreads is None:
                nthreads = self.nthreads
            else:
                assert isinstance(nthreads, int)
        else:
            nthreads = 1
        cell_selection = self._ensure_cell_selection(cell_key)
        graph_cell_selection = self._graph_cell_selection(graph_input)
        if not self._selection_artifacts_match(
            graph_cell_selection,
            cell_selection,
        ):
            raise ValueError("cell_key does not match the graph cell selection")
        cell_selection = graph_cell_selection
        artifact_scope = graph_input.scope
        arguments = TsneArguments(
            graph=graph_input,
            initialization=initialization_input,
            symmetric_graph=symmetric_graph,
            graph_upper_only=graph_upper_only,
            tsne_dims=tsne_dims,
            lambda_scale=lambda_scale,
            max_iter=max_iter,
            early_iter=early_iter,
            alpha=alpha,
            box_h=box_h,
            parallel=parallel,
            parallel_threads=nthreads,
            label=label,
            from_assay=from_assay,
            cell_key=cell_key,
            temp_file_loc=temp_file_loc,
            verbose=verbose,
            invalidate_cache=invalidate_cache,
        )
        record = arguments.to_record()
        planned = plan_cell_data_artifact(
            self.zw,
            scope=artifact_scope,
            assay=(
                graph_input.assay
                if graph_input.scope == "assay"
                else from_assay
                if artifact_scope == "assay"
                else None
            ),
            kind=arguments.artifact_kind,
            operation=arguments.operation,
            parameters=record.parameters,
            inputs=record.inputs,
            execution_options=record.execution_options,
            cell_selection=cell_selection,
            arrays={"values": ((graph_matrix.shape[0], tsne_dims), "f")},
            invalidate_cache=invalidate_cache,
        )
        columns = [
            self._col_renamer(
                selection.output_assay,
                cell_key,
                f"{label}{i + 1}",
            )
            for i in range(tsne_dims)
        ]
        preserved_displays = [column_display(self.zw, column) for column in columns]
        if planned.reused:
            artifact_group = as_zarr_group(
                self.zw[artifact_path(planned.ref)],
                name=planned.ref.artifact_id,
            )
            values = artifact_values(artifact_group, "values")
        else:
            import sys

            if sys.platform not in ["posix", "linux"]:
                raise RuntimeError(
                    f"{sys.platform} operating system is currently not supported."
                )
            from ...embeddings.sgtsne import run_sgtsne

            try:
                raw_embedding = np.asarray(
                    run_sgtsne(
                        graph_matrix,
                        ini_embed,
                        tsne_dims=tsne_dims,
                        max_iter=max_iter,
                        early_iter=early_iter,
                        alpha=alpha,
                        lambda_scale=lambda_scale,
                        box_h=box_h,
                        temp_file_loc=temp_file_loc,
                        verbose=verbose,
                        parallel=parallel,
                        nthreads=nthreads,
                    )
                )
            except (FileNotFoundError, ImportError) as exc:
                raise RuntimeError(
                    "SG-tSNE failed, possibly due to missing sgtsne executable or "
                    f"sgtsnepi package: {exc}"
                ) from exc
            if raw_embedding.shape != (tsne_dims, graph_matrix.shape[0]):
                raise ValueError(
                    "SG-tSNE returned an embedding with shape "
                    f"{raw_embedding.shape}; "
                    f"expected {(tsne_dims, graph_matrix.shape[0])}"
                )
            values = raw_embedding.T
            write_cell_data_artifact(
                self.zw,
                planned,
                {"values": values},
            )
        for i, column in enumerate(columns):
            self.cells.insert(
                column,
                values[:, i],
                key=cell_key,
                overwrite=True,
            )
        for i, column in enumerate(columns):
            link_cell_data_column(
                self.zw,
                column,
                planned.ref,
                value_name="values",
                value_index=i,
                default_display=continuous_display(values[:, i]),
                preserved_display=preserved_displays[i],
            )
        action = "Reused" if planned.reused else "Stored"
        logger.info(
            f"{action} {tsne_dims}-dimensional t-SNE embedding for {len(values)} cells"
        )
        return planned.ref

    def run_umap(
        self,
        graph: ArtifactRef | None = None,
        *,
        from_assay: str | None = None,
        cell_key: str | None = None,
        symmetric_graph: bool | None = False,
        graph_upper_only: bool | None = False,
        ini_embed: np.ndarray | None = None,
        umap_dims: int = 2,
        spread: float = 2.0,
        min_dist: float = 1,
        n_epochs: int = 300,
        repulsion_strength: float = 1.0,
        initial_alpha: float = 1.0,
        negative_sample_rate: float = 5,
        use_density_map: bool = False,
        dens_lambda: float = 2.0,
        dens_frac: float = 0.3,
        dens_var_shift: float = 0.1,
        random_seed: int = 4444,
        label: str = "UMAP",
        parallel: bool = False,
        nthreads: int | None = None,
        invalidate_cache: bool = False,
    ) -> ArtifactRef:
        """Runs UMAP algorithm using the precomputed cell-neighbourhood graph.
        The calculated UMAP coordinates are saved in the cell metadata table.

        Args:
            graph: Connectivity map or integrated graph to embed. The current
                   analysis chain of the assay is used when omitted.
            from_assay: Name of assay to be used. If no value is provided then the default assay will be used.
            cell_key: Cell key. Should be same as the one that was used in the desired graph. (Default value: 'I')
            symmetric_graph: This parameter is forwarded to `load_graph` and is same as there. (Default value: False)
            graph_upper_only: This parameter is forwarded to `load_graph` and is same as there. (Default value: False)
            ini_embed: Initial embedding coordinates for the cells in cell_key. Should have the same number of columns
                       as umap_dims. If not value is provided then the initial embedding is obtained using
                       `get_ini_embed`.
            umap_dims: Number of dimensions of UMAP embedding (Default value: 2)
            spread: Same as spread in UMAP package.  The effective scale of embedded points. In combination with
                    ``min_dist`` this determines how clustered/clumped the embedded points are.
            min_dist: Same as min_dist in UMAP package. The effective minimum distance between embedded points.
                      Smaller values will result in a more clustered/clumped embedding where nearby points on the
                      manifold are drawn closer together, while larger values will result on a more even dispersal of
                      points. The value should be set relative to the ``spread`` value, which determines the scale at
                      which embedded points will be spread out. (Default value: 1)
            n_epochs: Same as n_epochs in UMAP package. The number of epochs to be used in optimizing the
                      low dimensional embedding. Larger values may result in more accurate embeddings.
                      (Default value: 300)
            repulsion_strength: Same as repulsion_strength in UMAP package. Weighting applied to negative samples in
                                low dimensional embedding optimization. Values higher than one will result in greater
                                weight being given to negative samples. (Default value: 1.0)
            initial_alpha: Same as learning_rate in UMAP package. The initial learning rate for the embedding
                           optimization. (Default value: 1.0)
            negative_sample_rate: Same as negative_sample_rate in UMAP package. The number of negative samples to
                                  select per positive sample in the optimization process. Increasing this value will
                                  result in greater repulsive force being applied, greater optimization cost, but
                                  slightly more accuracy. (Default value: 5)
            use_density_map: If True, run densMAP (density-preserving UMAP) instead of standard UMAP.
            dens_lambda: densMAP density preservation strength (Default value: 2.0).
            dens_frac: Fraction of nearest neighbors used for local density estimation (Default value: 0.3).
            dens_var_shift: Variance shift for density correction (Default value: 0.1).
            random_seed: (Default value: 4444)
            label: base label for UMAP dimensions in the cell metadata column (Default value: 'UMAP')
            parallel: Whether to run UMAP in parallel mode. Setting value to True will use `nthreads` threads.
                      The results are not reproducible in parallel mode. (Default value: False)
            nthreads: If parallel=True then this number of threads will be used to run UMAP. By default, the `nthreads`
                      attribute of the class is used. (Default value: None)

        Returns:
            Reference to the embedding artifact backing the layout columns.
        """
        from ...embeddings.umap import fit_transform

        selection = resolve_graph_selection(
            self,
            graph,
            from_assay=from_assay,
            cell_key=cell_key,
        )
        from_assay = selection.from_assay
        cell_key = selection.cell_key
        graph_input = selection.graph_ref
        graph_matrix = self.load_graph(
            graph_input,
            from_assay=from_assay,
            cell_key=cell_key,
            symmetric=symmetric_graph,
            upper_only=graph_upper_only,
        )
        user_initialization = ini_embed is not None
        initialization_input: object
        if ini_embed is None:
            ini_embed, initialization_input = self._get_ini_embed(
                from_assay,
                cell_key,
                graph_input,
                umap_dims,
            )
        if ini_embed.shape != (graph_matrix.shape[0], umap_dims):
            raise ValueError(
                "Initial embedding has an invalid shape; expected "
                f"{(graph_matrix.shape[0], umap_dims)}"
            )
        if user_initialization:
            initialization_input = {"value_fingerprint": fingerprint_array(ini_embed)}
        if nthreads is None:
            nthreads = self.nthreads
        cell_selection = self._ensure_cell_selection(cell_key)
        graph_cell_selection = self._graph_cell_selection(graph_input)
        if not self._selection_artifacts_match(
            graph_cell_selection,
            cell_selection,
        ):
            raise ValueError("cell_key does not match the graph cell selection")
        cell_selection = graph_cell_selection
        effective_density_map = (
            use_density_map and graph_input.kind != "integrated_graph"
        )
        artifact_scope = graph_input.scope
        arguments = UmapArguments(
            graph=graph_input,
            initialization=initialization_input,
            symmetric_graph=symmetric_graph,
            graph_upper_only=graph_upper_only,
            umap_dims=umap_dims,
            spread=spread,
            min_dist=min_dist,
            n_epochs=n_epochs,
            repulsion_strength=repulsion_strength,
            initial_alpha=initial_alpha,
            negative_sample_rate=negative_sample_rate,
            use_density_map=effective_density_map,
            dens_lambda=dens_lambda,
            dens_frac=dens_frac,
            dens_var_shift=dens_var_shift,
            random_seed=random_seed,
            parallel=parallel,
            parallel_threads=nthreads if parallel else None,
            label=label,
            from_assay=from_assay,
            cell_key=cell_key,
            invalidate_cache=invalidate_cache,
        )
        record = arguments.to_record()
        planned = plan_cell_data_artifact(
            self.zw,
            scope=artifact_scope,
            assay=(
                graph_input.assay
                if graph_input.scope == "assay"
                else from_assay
                if artifact_scope == "assay"
                else None
            ),
            kind=arguments.artifact_kind,
            operation=arguments.operation,
            parameters=record.parameters,
            inputs=record.inputs,
            execution_options=record.execution_options,
            cell_selection=cell_selection,
            arrays={"values": ((graph_matrix.shape[0], umap_dims), "f")},
            invalidate_cache=invalidate_cache,
        )
        verbose = progress_enabled()

        if use_density_map and graph_input.kind == "integrated_graph":
            logger.warning(
                "DensMap is not available for integrated graphs. Running standard UMAP."
            )
        if effective_density_map:
            lineage = resolve_native_graph_inputs(self.zw, graph_input)
            knn_status = inspect_artifact(self.zw, lineage.neighbors)
            knn_loc = knn_status.path
            logger.trace(f"Loading KNN dists and indices from {knn_loc}")
            validate_distance_provenance(self.zw, lineage.neighbors)
            knn_group = as_zarr_group(self.zw[knn_loc], name=knn_loc)
            dists = np.asarray(
                as_zarr_array(knn_group["distances"], name="distances")[:]
            )
            indices = np.asarray(as_zarr_array(knn_group["indices"], name="indices")[:])
            dmat = csr_matrix(
                (
                    dists.flatten(),
                    (
                        np.repeat(range(indices.shape[0]), indices.shape[1]),
                        indices.flatten(),
                    ),
                ),
                shape=(indices.shape[0], indices.shape[0]),
            )
            # dmat = dmat.maximum(dmat.transpose()).todok()
            logger.trace("Created sparse KNN dists and indices")
            densmap_kwds = {
                "lambda": dens_lambda,
                "frac": dens_frac,
                "var_shift": dens_var_shift,
                "n_neighbors": dists.shape[1],
                "knn_dists": dmat,
            }
        else:
            densmap_kwds = {}

        if planned.reused:
            artifact_group = as_zarr_group(
                self.zw[artifact_path(planned.ref)],
                name=planned.ref.artifact_id,
            )
            t = artifact_values(artifact_group, "values")
        else:
            t, _a, _b = fit_transform(
                graph=graph_matrix.tocoo(),
                ini_embed=ini_embed,
                spread=spread,
                min_dist=min_dist,
                n_epochs=n_epochs,
                random_seed=random_seed,
                repulsion_strength=repulsion_strength,
                initial_alpha=initial_alpha,
                negative_sample_rate=negative_sample_rate,
                densmap_kwds=densmap_kwds,
                parallel=parallel,
                nthreads=nthreads,
                verbose=verbose,
            )
            write_cell_data_artifact(
                self.zw,
                planned,
                {"values": t},
            )

        columns = [
            self._col_renamer(
                selection.output_assay,
                cell_key,
                f"{label}{i + 1}",
            )
            for i in range(umap_dims)
        ]
        preserved_displays = [column_display(self.zw, column) for column in columns]
        for i, column in enumerate(columns):
            self.cells.insert(
                column,
                t[:, i],
                key=cell_key,
                overwrite=True,
            )
            link_cell_data_column(
                self.zw,
                column,
                planned.ref,
                value_name="values",
                value_index=i,
                default_display=continuous_display(t[:, i]),
                preserved_display=preserved_displays[i],
            )
        action = "Reused" if planned.reused else "Stored"
        logger.info(
            f"{action} {umap_dims}-dimensional UMAP embedding for {len(t)} cells"
        )
        return planned.ref
