import os
import shutil
from pathlib import Path
from uuid import uuid4

import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix, csr_matrix

from ..utils.logging import logger
from ..utils.process import system_call
from ..utils.progress import iter_progress


def export_knn_to_mtx(
    mtx: str,
    csr_graph: csr_matrix,
    batch_size: int = 1000,
) -> None:
    """Export a KNN matrix in Matrix Market format."""
    n_cells = csr_graph.shape[0]
    with open(mtx, "w") as handle:
        handle.write(
            "%%MatrixMarket matrix coordinate real general\n% Generated by Scarf\n"
        )
        handle.write(f"{n_cells} {n_cells} {csr_graph.nnz}\n")
        start = 0
        for end in iter_progress(
            range(batch_size, n_cells + batch_size, batch_size),
            desc="Saving KNN matrix in MTX format",
        ):
            if end > n_cells:
                end = n_cells
            subgraph = csr_graph[start:end].tocoo()
            frame = pd.DataFrame(
                {
                    "row": subgraph.row + start + 1,
                    "col": subgraph.col + 1,
                    "d": subgraph.data,
                }
            )
            frame.to_csv(
                handle,
                sep=" ",
                header=False,
                index=False,
                mode="a",
            )
            start = end
        if start != n_cells:
            raise ValueError(
                "ERROR: Internal loop count error in export_knn_to_mtx. "
                "Please report this bug"
            )


def run_sgtsne(
    graph: csr_matrix | coo_matrix,
    ini_embed: np.ndarray,
    *,
    tsne_dims: int = 2,
    max_iter: int = 500,
    early_iter: int = 200,
    alpha: int = 10,
    lambda_scale: float = 1.0,
    box_h: float = 0.7,
    temp_file_loc: str = ".",
    verbose: bool = True,
    parallel: bool = False,
    nthreads: int = 1,
) -> np.ndarray:
    """Run SG-t-SNE using the CLI or Python backend."""
    n_cells = graph.shape[0]
    ini_embed = np.asarray(ini_embed)
    if ini_embed.shape == (n_cells * tsne_dims,):
        ini_embed = ini_embed.reshape(n_cells, tsne_dims)
    if ini_embed.shape != (n_cells, tsne_dims):
        raise ValueError(
            f"ini_embed must have shape ({n_cells}, {tsne_dims}), got {ini_embed.shape}"
        )

    if shutil.which("sgtsne") is not None:
        uid = str(uuid4())
        knn_mtx_fn = Path(temp_file_loc, f"{uid}.mtx").resolve()
        export_knn_to_mtx(str(knn_mtx_fn), graph)
        ini_emb_fn = Path(temp_file_loc, f"{uid}.txt").resolve()
        with open(ini_emb_fn, "w") as handle:
            handle.write("\n".join(map(str, ini_embed.flatten())))
        out_fn = Path(temp_file_loc, f"{uid}_output.txt").resolve()
        threads = nthreads if parallel else 1
        command = (
            f"sgtsne -m {max_iter} -l {lambda_scale} -d {tsne_dims} "
            f"-e {early_iter} -p {threads} -a {alpha} -h {box_h} "
            f"-i {ini_emb_fn} -o {out_fn} {knn_mtx_fn}"
        )
        if verbose:
            system_call(command)
        else:
            os.system(command)
        try:
            embedding = np.asarray(
                pd.read_csv(out_fn, header=None, sep=" ")[
                    list(range(tsne_dims))
                ].values.T
            )
        finally:
            for path in (out_fn, knn_mtx_fn, ini_emb_fn):
                if path.exists():
                    path.unlink()
        return embedding

    try:
        from sgtsnepi import sgtsnepi
    except ImportError as exc:
        raise ImportError(
            "SG-t-SNE requires the sgtsne executable on PATH or the sgtsnepi package."
        ) from exc

    if parallel:
        logger.warning(
            "parallel=True is not supported by the sgtsnepi Python backend; "
            "running single-threaded"
        )

    return np.asarray(
        sgtsnepi(
            graph,
            y0=ini_embed.T,
            d=tsne_dims,
            max_iter=max_iter,
            early_exag=early_iter,
            lambda_par=lambda_scale,
            h=box_h,
            alpha=alpha,
            silent=not verbose,
        )
    )
