import shutil
import subprocess
from contextlib import AbstractContextManager, nullcontext
from pathlib import Path
from uuid import uuid4

import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix, csr_matrix

from ..utils.logging import logger
from ..utils.process import suppress_native_output
from ..utils.progress import iter_progress

_STDERR_TAIL_LINES = 20


def export_knn_to_mtx(
    mtx: str,
    csr_graph: csr_matrix,
    batch_size: int = 1000,
) -> None:
    """Export a KNN matrix in Matrix Market format."""
    n_cells = csr_graph.shape[0]
    with open(mtx, "w") as handle:
        handle.write(
            "%%MatrixMarket matrix coordinate real general\n% Generated by Scarf\n"
        )
        handle.write(f"{n_cells} {n_cells} {csr_graph.nnz}\n")
        start = 0
        for end in iter_progress(
            range(batch_size, n_cells + batch_size, batch_size),
            desc="Saving KNN matrix in MTX format",
        ):
            if end > n_cells:
                end = n_cells
            subgraph = csr_graph[start:end].tocoo()
            frame = pd.DataFrame(
                {
                    "row": subgraph.row + start + 1,
                    "col": subgraph.col + 1,
                    "d": subgraph.data,
                }
            )
            frame.to_csv(
                handle,
                sep=" ",
                header=False,
                index=False,
                mode="a",
            )
            start = end
        if start != n_cells:
            raise ValueError(
                "ERROR: Internal loop count error in export_knn_to_mtx. "
                "Please report this bug"
            )


def _run_sgtsne_executable(command: list[str], *, verbose: bool) -> None:
    """Run the SG-t-SNE executable and fail on a non-zero exit status."""
    completed = subprocess.run(
        command,
        stdout=subprocess.PIPE if verbose else subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
        errors="replace",
        check=False,
    )
    if verbose:
        for stream in (completed.stdout, completed.stderr):
            for line in (stream or "").splitlines():
                if line.strip():
                    logger.debug(line.strip())
    if completed.returncode != 0:
        tail = "\n".join(
            (completed.stderr or "").strip().splitlines()[-_STDERR_TAIL_LINES:]
        )
        message = f"sgtsne exited with status {completed.returncode}"
        raise RuntimeError(f"{message}: {tail}" if tail else message)


def run_sgtsne(
    graph: csr_matrix | coo_matrix,
    ini_embed: np.ndarray,
    *,
    tsne_dims: int = 2,
    max_iter: int = 500,
    early_iter: int = 200,
    alpha: int = 10,
    lambda_scale: float = 1.0,
    box_h: float = 0.7,
    temp_file_loc: str = ".",
    verbose: bool = True,
    parallel: bool = False,
    nthreads: int = 1,
) -> np.ndarray:
    """Run SG-t-SNE using the CLI or Python backend."""
    n_cells = graph.shape[0]
    ini_embed = np.asarray(ini_embed)
    if ini_embed.shape == (n_cells * tsne_dims,):
        ini_embed = ini_embed.reshape(n_cells, tsne_dims)
    if ini_embed.shape != (n_cells, tsne_dims):
        raise ValueError(
            f"ini_embed must have shape ({n_cells}, {tsne_dims}), got {ini_embed.shape}"
        )
    graph = graph.tocsr(copy=True)
    graph.eliminate_zeros()

    executable = shutil.which("sgtsne")
    if executable is not None:
        uid = str(uuid4())
        knn_mtx_fn = Path(temp_file_loc, f"{uid}.mtx").resolve()
        ini_emb_fn = Path(temp_file_loc, f"{uid}.txt").resolve()
        out_fn = Path(temp_file_loc, f"{uid}_output.txt").resolve()
        options = (
            ("-m", max_iter),
            ("-l", lambda_scale),
            ("-d", tsne_dims),
            ("-e", early_iter),
            ("-p", nthreads if parallel else 1),
            ("-a", alpha),
            ("-h", box_h),
            ("-i", ini_emb_fn),
            ("-o", out_fn),
        )
        command = [
            executable,
            *(str(part) for option in options for part in option),
            str(knn_mtx_fn),
        ]
        try:
            export_knn_to_mtx(str(knn_mtx_fn), graph)
            with open(ini_emb_fn, "w") as handle:
                handle.write("\n".join(map(str, ini_embed.flatten())))
            _run_sgtsne_executable(command, verbose=verbose)
            embedding = np.asarray(
                pd.read_csv(out_fn, header=None, sep=" ")[
                    list(range(tsne_dims))
                ].values.T
            )
        finally:
            for path in (out_fn, knn_mtx_fn, ini_emb_fn):
                if path.exists():
                    path.unlink()
        return embedding

    try:
        from sgtsnepi import sgtsnepi
    except ImportError as exc:
        raise ImportError(
            "SG-t-SNE requires the sgtsne executable on PATH or the sgtsnepi package."
        ) from exc

    if parallel:
        logger.warning(
            "parallel=True is not supported by the sgtsnepi Python backend; "
            "running single-threaded"
        )

    # sgtsnepi's own silent mode closes descriptors 1 and 2 for the rest of
    # the process, so quiet runs redirect them around the call instead.
    output: AbstractContextManager[None] = (
        nullcontext() if verbose else suppress_native_output()
    )
    with output:
        embedding = sgtsnepi(
            graph,
            y0=ini_embed.T,
            d=tsne_dims,
            max_iter=max_iter,
            early_exag=early_iter,
            lambda_par=lambda_scale,
            h=box_h,
            alpha=alpha,
            silent=False,
        )
    return np.asarray(embedding)
