"""Private bounded-memory R serialization reader."""

from ._lazy import LazyAtomicVector, LazyStringVector, LazyVector
from ._model import (
    AltRepValue,
    BytecodeValue,
    ClosureValue,
    EnvironmentValue,
    ExternalPointerValue,
    PairValue,
    PersistentValue,
    PromiseValue,
    RNode,
    RdsDocument,
    WeakReferenceValue,
    get_attribute,
    get_named,
    get_slot,
    iter_attributes,
    iter_named,
    iter_pairlist,
    symbol_name,
)
from ._parser import open_rds
from ._types import (
    R_INT_NA,
    RdsClosedError,
    RdsCompression,
    RdsEncoding,
    RdsError,
    RdsFormatError,
    RdsLimitError,
    RdsLimits,
    RdsMetadata,
    RdsSourceMetadata,
    RType,
)

__all__ = [
    "R_INT_NA",
    "AltRepValue",
    "BytecodeValue",
    "ClosureValue",
    "EnvironmentValue",
    "ExternalPointerValue",
    "LazyAtomicVector",
    "LazyStringVector",
    "LazyVector",
    "PairValue",
    "PersistentValue",
    "PromiseValue",
    "RNode",
    "RType",
    "RdsClosedError",
    "RdsCompression",
    "RdsDocument",
    "RdsEncoding",
    "RdsError",
    "RdsFormatError",
    "RdsLimitError",
    "RdsLimits",
    "RdsMetadata",
    "RdsSourceMetadata",
    "WeakReferenceValue",
    "get_attribute",
    "get_named",
    "get_slot",
    "iter_attributes",
    "iter_named",
    "iter_pairlist",
    "open_rds",
    "symbol_name",
]
