"""Plotting functions bound to a datastore instance."""

from collections.abc import Hashable, Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal

import numpy as np

from ..mapping.models import MappingResult
from ..mapping.reference import MappingReference
from ..plotting._contracts import (
    CategoricalScale,
    CellField,
    ColorScale,
    DensityOverlay,
    DistKind,
    FeatureRef,
    FrameStyle,
    Highlight,
    LegendLoc,
    NormalizationSpec,
    SizeScale,
    StudyDesign,
)
from ..plotting._figure import PlotResult
from ..plotting.recipes import PlotRecipe, PlotRecipeResult
from ..storage.refs import ArtifactRef

if TYPE_CHECKING:
    from .datastore import DataStore


class DataStorePlotAccessor:
    """Datastore-bound facade for store-first plotting functions."""

    __slots__ = ("_store",)

    def __init__(self, store: "DataStore") -> None:
        self._store = store

    def embedding(
        self,
        *,
        layout_key: str | Sequence[str],
        color_by: (
            "str"
            " | FeatureRef"
            " | CellField"
            " | Sequence[str | FeatureRef | CellField]"
            " | None"
        ) = None,
        facet_by: str | None = None,
        facet_order: Sequence[Any] | None = None,
        cell_key: str = "I",
        from_assay: str | None = None,
        normalization: "NormalizationSpec | None" = None,
        point_size: float | None = None,
        point_sizes: "np.ndarray | Sequence[float] | None" = None,
        point_size_range: tuple[float, float] = (1.0, 28.0),
        point_edgecolor: str | None = None,
        point_edgewidth: float | None = None,
        point_alpha: float = 1.0,
        sort_values: bool = False,
        color_scale: "ColorScale | None" = None,
        categorical_scale: "CategoricalScale | None" = None,
        default_color: str = "steelblue",
        missing_color: str | None = None,
        clip_fraction: float = 0.0,
        subset_by: str | None = None,
        groups: Sequence[Any] | None = None,
        n_columns: int | None = None,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        legend_loc: "LegendLoc" = "auto",
        max_on_data_labels: int = 40,
        show_legend: bool = True,
        show_titles: bool = True,
        frame: "FrameStyle" = "minimal",
        density_overlay: "DensityOverlay | None" = None,
        highlight: "Highlight | None" = None,
        seed: int | None = None,
        rasterize_threshold: int = 50_000,
        show: bool = True,
    ) -> "PlotResult":
        """Plot cells in a stored two-dimensional embedding."""
        from ..plotting import embedding

        return embedding(
            self._store,
            layout_key=layout_key,
            color_by=color_by,
            facet_by=facet_by,
            facet_order=facet_order,
            cell_key=cell_key,
            from_assay=from_assay,
            normalization=normalization,
            point_size=point_size,
            point_sizes=point_sizes,
            point_size_range=point_size_range,
            point_edgecolor=point_edgecolor,
            point_edgewidth=point_edgewidth,
            point_alpha=point_alpha,
            sort_values=sort_values,
            color_scale=color_scale,
            categorical_scale=categorical_scale,
            default_color=default_color,
            missing_color=missing_color,
            clip_fraction=clip_fraction,
            subset_by=subset_by,
            groups=groups,
            n_columns=n_columns,
            target=target,
            figsize=figsize,
            theme=theme,
            legend_loc=legend_loc,
            max_on_data_labels=max_on_data_labels,
            show_legend=show_legend,
            show_titles=show_titles,
            frame=frame,
            density_overlay=density_overlay,
            highlight=highlight,
            seed=seed,
            rasterize_threshold=rasterize_threshold,
            show=show,
        )

    def embedding_raster(
        self,
        *,
        layout_key: str,
        color_by: "str | CellField | None" = None,
        cell_key: str = "I",
        pixels: int = 400,
        block_rows: int | None = None,
        color_scale: "ColorScale | None" = None,
        missing_color: str = "white",
        subset_by: str | None = None,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        seed: int = 0,
        show: bool = True,
    ) -> "PlotResult":
        """Rasterize continuous cell metadata over a stored embedding."""
        from ..plotting import embedding_raster

        return embedding_raster(
            self._store,
            layout_key=layout_key,
            color_by=color_by,
            cell_key=cell_key,
            pixels=pixels,
            block_rows=block_rows,
            color_scale=color_scale,
            missing_color=missing_color,
            subset_by=subset_by,
            target=target,
            figsize=figsize,
            theme=theme,
            seed=seed,
            show=show,
        )

    def mapping_score(
        self,
        result: MappingResult | ArtifactRef | str,
        *,
        reference: MappingReference | None = None,
        target_groups: Sequence[Any] | np.ndarray | None = None,
        layout_key: str | None = None,
        kind: Literal["embedding", "histogram"] = "embedding",
        query_assay: str | None = None,
        log_transform: bool = True,
        multiplier: float = 1000,
        weighted: bool = True,
        fixed_weight: float = 0.1,
        bins: int = 40,
        point_size: float | None = None,
        color_scale: ColorScale | None = None,
        categorical_scale: CategoricalScale | None = None,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> PlotResult:
        """Plot reference-cell mapping scores for one or more query groups."""
        from ..plotting import mapping_score

        return mapping_score(
            self._store,
            result,
            reference=reference,
            target_groups=target_groups,
            layout_key=layout_key,
            kind=kind,
            query_assay=query_assay,
            log_transform=log_transform,
            multiplier=multiplier,
            weighted=weighted,
            fixed_weight=fixed_weight,
            bins=bins,
            point_size=point_size,
            color_scale=color_scale,
            categorical_scale=categorical_scale,
            target=target,
            figsize=figsize,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )

    def mapping_evidence(
        self,
        result: MappingResult | ArtifactRef | str,
        *,
        reference: MappingReference | None = None,
        reference_class_group: str,
        target_groups: Sequence[Any] | np.ndarray | None = None,
        metrics: Sequence[str] = (
            "voteFraction",
            "topTwoMargin",
            "voteEntropy",
            "referenceDistancePercentile",
        ),
        kind: Literal["histogram", "box", "embedding"] = "histogram",
        reference_layout_key: str | None = None,
        bins: int = 30,
        query_assay: str | None = None,
        threshold_fraction: float = 0.5,
        na_val: str = "NA",
        max_distance: float | None = None,
        categorical_scale: CategoricalScale | None = None,
        color_scale: ColorScale | None = None,
        point_size: float | None = None,
        show_unknown: bool = True,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> PlotResult:
        """Plot query-level label-transfer evidence."""
        from ..plotting import mapping_evidence

        return mapping_evidence(
            self._store,
            result,
            reference=reference,
            reference_class_group=reference_class_group,
            target_groups=target_groups,
            metrics=metrics,
            kind=kind,
            reference_layout_key=reference_layout_key,
            bins=bins,
            query_assay=query_assay,
            threshold_fraction=threshold_fraction,
            na_val=na_val,
            max_distance=max_distance,
            categorical_scale=categorical_scale,
            color_scale=color_scale,
            point_size=point_size,
            show_unknown=show_unknown,
            target=target,
            figsize=figsize,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )

    def mapping_confusion(
        self,
        result: MappingResult | ArtifactRef | str,
        *,
        reference: MappingReference | None = None,
        reference_class_group: str,
        known_labels: Sequence[Any] | np.ndarray,
        normalize: Literal["none", "true", "predicted", "all"] = "true",
        known_order: Sequence[Any] | None = None,
        predicted_order: Sequence[Any] | None = None,
        query_assay: str | None = None,
        threshold_fraction: float = 0.5,
        na_val: str = "NA",
        max_distance: float | None = None,
        color_scale: ColorScale | None = None,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> PlotResult:
        """Plot known query labels against transferred labels."""
        from ..plotting import mapping_confusion

        return mapping_confusion(
            self._store,
            result,
            reference=reference,
            reference_class_group=reference_class_group,
            known_labels=known_labels,
            normalize=normalize,
            known_order=known_order,
            predicted_order=predicted_order,
            query_assay=query_assay,
            threshold_fraction=threshold_fraction,
            na_val=na_val,
            max_distance=max_distance,
            color_scale=color_scale,
            target=target,
            figsize=figsize,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )

    def mapping_calibration(
        self,
        result: MappingResult | ArtifactRef | str,
        *,
        reference: MappingReference | None = None,
        reference_class_group: str,
        known_labels: Sequence[Any] | np.ndarray,
        metric: str = "voteFraction",
        direction: Literal["auto", "higher", "lower"] = "auto",
        thresholds: Sequence[float] | np.ndarray | None = None,
        n_thresholds: int = 50,
        chosen_threshold: float | None = None,
        query_assay: str | None = None,
        na_val: str = "NA",
        max_distance: float | None = None,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        show: bool = True,
    ) -> PlotResult:
        """Plot held-out label accuracy against retained mapping coverage."""
        from ..plotting import mapping_calibration

        return mapping_calibration(
            self._store,
            result,
            reference=reference,
            reference_class_group=reference_class_group,
            known_labels=known_labels,
            metric=metric,
            direction=direction,
            thresholds=thresholds,
            n_thresholds=n_thresholds,
            chosen_threshold=chosen_threshold,
            query_assay=query_assay,
            na_val=na_val,
            max_distance=max_distance,
            target=target,
            figsize=figsize,
            theme=theme,
            show=show,
        )

    def mapping_projection(
        self,
        result: MappingResult | ArtifactRef | str,
        *,
        reference: MappingReference | None = None,
        reference_layout_key: str,
        reference_groups: str | Sequence[Any] | np.ndarray | None = None,
        target_groups: Sequence[Any] | np.ndarray | None = None,
        reference_class_group: str | None = None,
        threshold_fraction: float = 0.5,
        na_val: str = "NA",
        query_assay: str | None = None,
        ref_name: str = "reference",
        reference_mode: Literal["background", "groups"] = "background",
        categorical_scale: CategoricalScale | None = None,
        point_size: float | None = None,
        reference_alpha: float = 0.22,
        target_alpha: float = 0.95,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> PlotResult:
        """Plot query cells projected into an unchanged reference layout."""
        from ..plotting import mapping_projection

        return mapping_projection(
            self._store,
            result,
            reference=reference,
            reference_layout_key=reference_layout_key,
            reference_groups=reference_groups,
            target_groups=target_groups,
            reference_class_group=reference_class_group,
            threshold_fraction=threshold_fraction,
            na_val=na_val,
            query_assay=query_assay,
            ref_name=ref_name,
            reference_mode=reference_mode,
            categorical_scale=categorical_scale,
            point_size=point_size,
            reference_alpha=reference_alpha,
            target_alpha=target_alpha,
            target=target,
            figsize=figsize,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )

    def dotplot(
        self,
        *,
        features: (
            "Sequence[str | FeatureRef] | Mapping[str, Sequence[str | FeatureRef]]"
        ),
        group_by: str | tuple[str, ...],
        cell_key: str = "I",
        from_assay: str | None = None,
        sample_by: str | None = None,
        study_design: "StudyDesign | None" = None,
        normalization: "NormalizationSpec | None" = None,
        expression_cutoff: float = 0.0,
        standardize: str = "none",
        color_scale: "ColorScale | None" = None,
        size_scale: "SizeScale | None" = None,
        categorical_scale: "CategoricalScale | None" = None,
        group_order: Sequence[Any] | None = None,
        feature_order: Sequence[str] | None = None,
        swap_axes: bool = False,
        marker_edgecolor: str | None = None,
        marker_linewidth: float = 0.3,
        label_wrap: int | None = None,
        italicize_features: bool = False,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        max_figure_width: float | None = 7.5,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> "PlotResult":
        """Summarize feature expression as a dot plot."""
        from ..plotting import dotplot

        return dotplot(
            self._store,
            features=features,
            group_by=group_by,
            cell_key=cell_key,
            from_assay=from_assay,
            sample_by=sample_by,
            study_design=study_design,
            normalization=normalization,
            expression_cutoff=expression_cutoff,
            standardize=standardize,
            color_scale=color_scale,
            size_scale=size_scale,
            categorical_scale=categorical_scale,
            group_order=group_order,
            feature_order=feature_order,
            swap_axes=swap_axes,
            marker_edgecolor=marker_edgecolor,
            marker_linewidth=marker_linewidth,
            label_wrap=label_wrap,
            italicize_features=italicize_features,
            target=target,
            figsize=figsize,
            max_figure_width=max_figure_width,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )

    def matrixplot(
        self,
        *,
        features: (
            "Sequence[str | FeatureRef] | Mapping[str, Sequence[str | FeatureRef]]"
        ),
        group_by: str | tuple[str, ...],
        cell_key: str = "I",
        from_assay: str | None = None,
        sample_by: str | None = None,
        study_design: "StudyDesign | None" = None,
        normalization: "NormalizationSpec | None" = None,
        expression_cutoff: float = 0.0,
        value: str = "mean",
        standardize: str = "none",
        color_scale: "ColorScale | None" = None,
        feature_order: Sequence[Any] | None = None,
        group_order: Sequence[Any] | None = None,
        cluster_features: bool = False,
        cluster_groups: bool = False,
        cluster_method: str = "average",
        cluster_metric: str = "euclidean",
        row_annotations: (
            Mapping[str, Mapping[Any, Any] | Sequence[Any]] | None
        ) = None,
        column_annotations: (
            Mapping[str, Mapping[Any, Any] | Sequence[Any]] | None
        ) = None,
        annotation_scales: Mapping[str, CategoricalScale] | None = None,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> "PlotResult":
        """Summarize feature expression as a matrix plot."""
        from ..plotting import matrixplot

        return matrixplot(
            self._store,
            features=features,
            group_by=group_by,
            cell_key=cell_key,
            from_assay=from_assay,
            sample_by=sample_by,
            study_design=study_design,
            normalization=normalization,
            expression_cutoff=expression_cutoff,
            value=value,
            standardize=standardize,
            color_scale=color_scale,
            feature_order=feature_order,
            group_order=group_order,
            cluster_features=cluster_features,
            cluster_groups=cluster_groups,
            cluster_method=cluster_method,
            cluster_metric=cluster_metric,
            row_annotations=row_annotations,
            column_annotations=column_annotations,
            annotation_scales=annotation_scales,
            target=target,
            figsize=figsize,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )

    def composition(
        self,
        *,
        category_by: str,
        cell_key: str = "I",
        sample_by: str | None = None,
        subject_by: str | None = None,
        pair_by: str | None = None,
        condition_by: str | None = None,
        study_design: "StudyDesign | None" = None,
        kind: Literal["stacked", "per_sample"] = "stacked",
        show_summary: bool = True,
        uncertainty: Literal["none", "sd", "se", "ci95"] | None = None,
        categorical_scale: "CategoricalScale | None" = None,
        bar_width: float = 0.82,
        bar_gap: float = 0.12,
        segment_edgecolor: str | None = None,
        segment_linewidth: float = 0.5,
        show_percent_labels: bool = False,
        label_min_fraction: float = 0.08,
        percent_format: str = "{:.0%}",
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        max_figure_width: float | None = 7.5,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> "PlotResult":
        """Plot category composition for the selected cells."""
        from ..plotting import composition

        return composition(
            self._store,
            category_by=category_by,
            cell_key=cell_key,
            sample_by=sample_by,
            subject_by=subject_by,
            pair_by=pair_by,
            condition_by=condition_by,
            study_design=study_design,
            kind=kind,
            show_summary=show_summary,
            uncertainty=uncertainty,
            categorical_scale=categorical_scale,
            bar_width=bar_width,
            bar_gap=bar_gap,
            segment_edgecolor=segment_edgecolor,
            segment_linewidth=segment_linewidth,
            show_percent_labels=show_percent_labels,
            label_min_fraction=label_min_fraction,
            percent_format=percent_format,
            target=target,
            figsize=figsize,
            max_figure_width=max_figure_width,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )

    def distribution(
        self,
        keys: ("str | CellField | FeatureRef | Sequence[str | CellField | FeatureRef]"),
        *,
        group_by: str | None = None,
        groups: Sequence[Any] | None = None,
        split_by: str | None = None,
        sample_by: str | None = None,
        study_design: "StudyDesign | None" = None,
        sample_stat: Literal["mean", "median", "fraction"] = "mean",
        expression_cutoff: float = 0.0,
        subset_by: str | None = None,
        cell_key: str | None = "I",
        from_assay: str | None = None,
        normalization: "NormalizationSpec | None" = None,
        categorical_scale: "CategoricalScale | None" = None,
        split_scale: "CategoricalScale | None" = None,
        kind: "DistKind" = "violin",
        bins: int = 40,
        max_points: int = 10000,
        point_size: float = 0.8,
        point_alpha: float = 0.28,
        seed: int = 0,
        color: str = "steelblue",
        orientation: Literal["vertical", "horizontal"] = "vertical",
        row_standardize: bool = False,
        share_y: bool | None = None,
        violin_inner: str | None = "quartile",
        violin_linewidth: float = 0.8,
        violin_alpha: float = 0.9,
        italicize_features: bool = False,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        max_figure_width: float | None = 7.5,
        title: str | None = None,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> "PlotResult":
        """Plot distributions of cell metadata or feature values."""
        from ..plotting import distribution

        return distribution(
            self._store,
            keys,
            group_by=group_by,
            groups=groups,
            split_by=split_by,
            sample_by=sample_by,
            study_design=study_design,
            sample_stat=sample_stat,
            expression_cutoff=expression_cutoff,
            subset_by=subset_by,
            cell_key=cell_key,
            from_assay=from_assay,
            normalization=normalization,
            categorical_scale=categorical_scale,
            split_scale=split_scale,
            kind=kind,
            bins=bins,
            max_points=max_points,
            point_size=point_size,
            point_alpha=point_alpha,
            seed=seed,
            color=color,
            orientation=orientation,
            row_standardize=row_standardize,
            share_y=share_y,
            violin_inner=violin_inner,
            violin_linewidth=violin_linewidth,
            violin_alpha=violin_alpha,
            italicize_features=italicize_features,
            target=target,
            figsize=figsize,
            max_figure_width=max_figure_width,
            title=title,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )

    def marker_heatmap(
        self,
        *,
        from_assay: str | None = None,
        group_key: str | None = None,
        cell_key: str | None = None,
        topn: int = 5,
        log_transform: bool | None = None,
        vmin: float = -1,
        vmax: float = 2,
        figsize: tuple[float, float] | None = None,
        fontsize: float = 10,
        width_factor: float = 0.03,
        height_factor: float = 0.02,
        cmap: Any = "magma_r",
        color_scale: "ColorScale | None" = None,
        row_order: Sequence[Any] | None = None,
        column_order: Sequence[Any] | None = None,
        cluster_rows: bool = True,
        cluster_columns: bool = True,
        cluster_method: str = "ward",
        cluster_metric: str = "euclidean",
        row_annotations: (
            Mapping[str, Mapping[Any, Any] | Sequence[Any]] | None
        ) = None,
        column_annotations: (
            Mapping[str, Mapping[Any, Any] | Sequence[Any]] | None
        ) = None,
        annotation_scales: Mapping[str, CategoricalScale] | None = None,
        target: Any | None = None,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
        **heatmap_kwargs: Any,
    ) -> "PlotResult":
        """Plot the stored marker table as a heatmap."""
        from ..plotting import marker_heatmap

        return marker_heatmap(
            self._store,
            from_assay=from_assay,
            group_key=group_key,
            cell_key=cell_key,
            topn=topn,
            log_transform=log_transform,
            vmin=vmin,
            vmax=vmax,
            figsize=figsize,
            fontsize=fontsize,
            width_factor=width_factor,
            height_factor=height_factor,
            cmap=cmap,
            color_scale=color_scale,
            row_order=row_order,
            column_order=column_order,
            cluster_rows=cluster_rows,
            cluster_columns=cluster_columns,
            cluster_method=cluster_method,
            cluster_metric=cluster_metric,
            row_annotations=row_annotations,
            column_annotations=column_annotations,
            annotation_scales=annotation_scales,
            target=target,
            theme=theme,
            show_legend=show_legend,
            show=show,
            **heatmap_kwargs,
        )

    def run_recipe(
        self,
        recipe: "PlotRecipe | str | Path",
        *,
        artifacts: Mapping[str, Any] | None = None,
        targets: Mapping[str, Any] | None = None,
        output_dir: str | Path | None = None,
        show: bool = False,
        continue_on_error: bool = False,
    ) -> "PlotRecipeResult":
        """Run a declarative plotting recipe against this datastore."""
        from ..plotting import run_recipe

        return run_recipe(
            self._store,
            recipe,
            artifacts=artifacts,
            targets=targets,
            output_dir=output_dir,
            show=show,
            continue_on_error=continue_on_error,
        )

    def cluster_connectivity(
        self,
        *,
        group_by: str,
        layout_key: str,
        cell_key: str = "I",
        from_assay: str | None = None,
        feat_key: str | None = None,
        graph_loc: str | None = None,
        position: Literal["median", "mean"] = "median",
        positions: Mapping[Any, tuple[float, float]] | None = None,
        categorical_scale: "CategoricalScale | None" = None,
        size_scale: "SizeScale | None" = None,
        minimum_edge_weight: float = 0.02,
        max_edges_per_node: int | None = None,
        show_cells: bool = False,
        cell_size: float | None = None,
        cell_alpha: float = 0.3,
        cell_color: str | None = None,
        node_edgecolor: str | None = None,
        node_linewidth: float = 0.8,
        edge_color: str | None = None,
        edge_alpha: float = 0.45,
        edge_width_range: tuple[float, float] = (0.4, 5.0),
        labels: bool = True,
        target: Any | None = None,
        figsize: tuple[float, float] | None = None,
        theme: str = "notebook",
        show: bool = True,
    ) -> "PlotResult":
        """Summarize cell graph connectivity between embedding clusters."""
        from ..plotting import cluster_connectivity

        return cluster_connectivity(
            self._store,
            group_by=group_by,
            layout_key=layout_key,
            cell_key=cell_key,
            from_assay=from_assay,
            feat_key=feat_key,
            graph_loc=graph_loc,
            position=position,
            positions=positions,
            categorical_scale=categorical_scale,
            size_scale=size_scale,
            minimum_edge_weight=minimum_edge_weight,
            max_edges_per_node=max_edges_per_node,
            show_cells=show_cells,
            cell_size=cell_size,
            cell_alpha=cell_alpha,
            cell_color=cell_color,
            node_edgecolor=node_edgecolor,
            node_linewidth=node_linewidth,
            edge_color=edge_color,
            edge_alpha=edge_alpha,
            edge_width_range=edge_width_range,
            labels=labels,
            target=target,
            figsize=figsize,
            theme=theme,
            show=show,
        )

    def cluster_tree(
        self,
        *,
        from_assay: str | None = None,
        cell_key: str | None = None,
        feat_key: str | None = None,
        integrated_graph: str | None = None,
        cluster_key: str | None = None,
        fill_by_value: str | None = None,
        force_ints_as_cats: bool = True,
        width: float = 1,
        lvr_factor: float = 0.5,
        vert_gap: float = 0.2,
        min_node_size: float = 10,
        node_size_multiplier: float = 10_000.0,
        node_power: float = 1.2,
        root_size: float = 100,
        non_leaf_size: float = 10,
        show_labels: bool = True,
        fontsize: float = 10,
        root_color: str = "#C0C0C0",
        non_leaf_color: str = "k",
        cmap: str = "tab20",
        color_key: dict[Any, str] | None = None,
        edgecolors: str = "k",
        edgewidth: float = 1,
        alpha: float = 0.7,
        figsize: tuple[float, float] = (5, 5),
        ax: Any = None,
        theme: str = "notebook",
        show: bool = True,
    ) -> "PlotResult":
        """Plot a stored hierarchical clustering tree."""
        from ..plotting import cluster_tree

        return cluster_tree(
            self._store,
            from_assay=from_assay,
            cell_key=cell_key,
            feat_key=feat_key,
            integrated_graph=integrated_graph,
            cluster_key=cluster_key,
            fill_by_value=fill_by_value,
            force_ints_as_cats=force_ints_as_cats,
            width=width,
            lvr_factor=lvr_factor,
            vert_gap=vert_gap,
            min_node_size=min_node_size,
            node_size_multiplier=node_size_multiplier,
            node_power=node_power,
            root_size=root_size,
            non_leaf_size=non_leaf_size,
            show_labels=show_labels,
            fontsize=fontsize,
            root_color=root_color,
            non_leaf_color=non_leaf_color,
            cmap=cmap,
            color_key=color_key,
            edgecolors=edgecolors,
            edgewidth=edgewidth,
            alpha=alpha,
            figsize=figsize,
            ax=ax,
            theme=theme,
            show=show,
        )

    def pseudotime_heatmap(
        self,
        *,
        from_assay: str | None = None,
        cell_key: str | None = None,
        feat_key: str | None = None,
        feature_cluster_key: str | None = None,
        pseudotime_key: str | None = None,
        show_features: list[str] | None = None,
        feature_order: Sequence[str] | None = None,
        feature_cluster_order: Sequence[Any] | None = None,
        figsize: tuple[float, float] = (5, 10),
        vmin: float = -2.0,
        vmax: float = 2.0,
        heatmap_cmap: str | None = None,
        pseudotime_cmap: str | None = None,
        clusterbar_cmap: str | None = None,
        color_scale: "ColorScale | None" = None,
        feature_cluster_scale: "CategoricalScale | None" = None,
        pseudotime_scale: "ColorScale | None" = None,
        tick_fontsize: int = 10,
        axis_fontsize: int = 12,
        feature_label_fontsize: int = 12,
        target: Mapping[Hashable, Any] | None = None,
        theme: str = "notebook",
        show_legend: bool = True,
        show: bool = True,
    ) -> "PlotResult":
        """Plot feature profiles ordered by stored pseudotime."""
        from ..plotting import pseudotime_heatmap

        return pseudotime_heatmap(
            self._store,
            from_assay=from_assay,
            cell_key=cell_key,
            feat_key=feat_key,
            feature_cluster_key=feature_cluster_key,
            pseudotime_key=pseudotime_key,
            show_features=show_features,
            feature_order=feature_order,
            feature_cluster_order=feature_cluster_order,
            figsize=figsize,
            vmin=vmin,
            vmax=vmax,
            heatmap_cmap=heatmap_cmap,
            pseudotime_cmap=pseudotime_cmap,
            clusterbar_cmap=clusterbar_cmap,
            color_scale=color_scale,
            feature_cluster_scale=feature_cluster_scale,
            pseudotime_scale=pseudotime_scale,
            tick_fontsize=tick_fontsize,
            axis_fontsize=axis_fontsize,
            feature_label_fontsize=feature_label_fontsize,
            target=target,
            theme=theme,
            show_legend=show_legend,
            show=show,
        )
